In [2]:
import numpy as np

QUESTION 1

In [5]:
my_list = [2.2,3.5,6.8,4.6,5.5]
arr_list = np.array(my_list, dtype = float)
my_tuple = (2.2,3.5,6.8,4.6,5.5)
arr_tuple = np.array(my_tuple, dtype = float)
print("Array From List: ",arr_list)
print("Array From Tuple: ",arr_tuple)

Array From List:  [2.2 3.5 6.8 4.6 5.5]
Array From Tuple:  [2.2 3.5 6.8 4.6 5.5]


QUESTION 2

In [11]:
my_ar = np.array([0,1,2,3,4,5,6,7,8,9])
sl = my_ar[3:8]
print("Slicing Result :", sl)
inde = my_ar[[2,4,6]]
print("Indexing Result :", inde)
boolean_condition = my_ar % 2 == 0
print(boolean_condition)
boolean_indexing_result = my_ar[boolean_condition]
print("Boolean array indexing result:", boolean_indexing_result)

Slicing Result : [3 4 5 6 7]
Indexing Result : [2 4 6]
[ True False  True False  True False  True False  True False]
Boolean array indexing result: [0 2 4 6 8]


QUESTION 3

In [3]:
my_array = np.array([10,5,8,2,4,9])
min_va = np.min(my_array)
max_va = np.max(my_array)
sum_va = np.sum(my_array)
cumi_va = np.cumsum(my_array)
print("Original Array: ",my_array)
print("Min Value: ",min_va)
print("Max Value: ",max_va)
print("Sum Value: ",sum_va)
print("Cumulative Sum: ",cumi_va)

Original Array:  [10  5  8  2  4  9]
Min Value:  2
Max Value:  10
Sum Value:  38
Cumulative Sum:  [10 15 23 25 29 38]


QUESTION 4

In [5]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]],)
sha = a.shape
size = a.size
dime = a.ndim
dattype = a.dtype
print("Original Array")
print(a)
print("Number Of Dimensions (ndim) : ",dime)
print("Shape Of The Array : ", sha)
print("Total Number Of Elements (size) : ", size)
print("Data Type : ", dattype)

Original Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number Of Dimensions (ndim) :  2
Shape Of The Array :  (3, 3)
Total Number Of Elements (size) :  9
Data Type :  int32


QUESTION CASE STUDY

In [ ]:
stud_a = np.random.randint(0,101,(5,4))
print(stud_a)
pyth_a = stud_a[0:5,0:1]
math_a = stud_a[0:5,1:2]
sci_a = stud_a[0:5,2:3]
eng_a = stud_a[0:5,3:4]
print("Python Marks \n",pyth_a)
print("Average of Maths Marks \n",np.mean(pyth_a))
print("Math Marks \n",math_a)
print("Average of Maths Marks \n",np.mean(math_a))
print("Science Marks\n",sci_a)
print("Average of Maths Marks \n",np.mean(sci_a))
print("English Marks\n",eng_a)
print("Average of Maths Marks \n",np.mean(eng_a))

LAB 2 Numpy Library: Linear Algebra

In [1]:
import numpy as np

Question 1 : To Find Rank Determinant and Trace

In [ ]:
#input the matrix 
matrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
#calculate the rank of the matrix
rank = np.linalg.matrix_rank(matrix)
#calculate the determinant of the matrix
determinant = np.linalg.det(matrix)
# Calculate the trace of the matrix
# FYI- the trace of the matrix means its the sum of the elements on its main diagonal, which
#runs from the top left to the bottom right of the matrix.
trace = np.trace(matrix)
# Print the results
print(matrix)
print(f"Rank: {rank}")
print(f"Determinant: {determinant}")
print(f"Trace: {trace}")

Question 2 : Eigen values of Matrix

In [11]:
#Input the matrix (replace this with your own matrix)
matrix = np.array([[1, 2], [2, 3]])
#Calculate the eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(matrix)
#Print the eigenvalues
print("Matrix:")
print(matrix)
print("Eigenvalues:")
print(eigenvalues)

Matrix:
[[1 2]
 [2 3]]
Eigenvalues:
[-0.23606798  4.23606798]


Question 3 : Matrix and vector products (dot, inner, outer, product), matrix exponentiation

In [ ]:
# Create matrices and vectors (replace these with your own)
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])
vector_x = np.array([1, 2])
vector_y = np.array([3, 4])
# Dot product of two vectors
dot_product = np.dot(vector_x, vector_y)
# Inner product (dot product) of two matrices
inner_product = np.inner(matrix_A,matrix_B)
# Outer product Of two vectors
outer_product = np.outer(vector_x,vector_y)
# Matrix product (matrix multiplication)
matrix_product = np.matmul(matrix_A, matrix_B)
# Matrix exponentiation
exponent = 2 # Replace with the desired exponent
matrix_exponential = np.linalg.matrix_power(matrix_A, exponent)
# Print the results
print("Vector x:" , vector_x)
print("Vector y:" , vector_y)
print("Matrix A:")
print(matrix_A)
print("Matrix B:")
print(matrix_B)
print("Dot product of x and y:", dot_product)
print("Inner product of A and B:")
print(inner_product)
print("Outer product of x and y:")
print(outer_product)
print("Matrix product of A and B:")
print(matrix_product)
print(f"Matrix A raised to the power {exponent}:")
print(matrix_exponential)

Question 4 : Solve a linear matrix equation, or system of linear scalar equations

In [ ]:
# Define the coefficients matrix (A) and the right-hand side vector (b)
# Replace these with your own values
A = np.array([[2, 1],[1, 3]])
b = np.array([3, 9])
# Solve the linear system of equations
solution = np.linalg.solve(A, b)
# Print the solution
print("Coeffcient matrix (A): ")
print(A)
print("Right-hand side vector (b):")
print(b)
print("Solution vector (x):")
print(solution)

Pandas Library

In [27]:
import pandas as pd

Question 1 : Implement Pandas Series with Labels

In [28]:
# Create a pandas Series with labels
data = {'A':10,'B':20,'C':30, 'D':40}
my_series = pd.Series(data)
# Print the Series
print("Pandas Series: ")
print(my_series)
# Accessing elements by label
print("\nAccessing elements by label:")
print("Value at label 'A':",my_series['A'])
print("Value at label 'C':",my_series['C'])
# Accessing elements by position
print("\nAccessing elements by position:")
print("The First element:", my_series[0])
print("The second element:", my_series[1])
# Arithmetic operations on the Series
print("\nArithmetic operations on the Series:" )
result = my_series * 2
print("Series multiplied by 2:")
print(result)
#Filtering elements
print("\nFiltering elements ")
filtered_series = my_series[my_series>20]
print("Elememts Greater Than 20:")
print(filtered_series)

Pandas Series: 
A    10
B    20
C    30
D    40
dtype: int64

Accessing elements by label:
Value at label 'A': 10
Value at label 'C': 30

Accessing elements by position:
The First element: 10
The second element: 20

Arithmetic operations on the Series:
Series multiplied by 2:
A    20
B    40
C    60
D    80
dtype: int64

Filtering elements 
Elememts Greater Than 20:
C    30
D    40
dtype: int64


C:\Users\nidhi\AppData\Local\Temp\ipykernel_16904\804799052.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("The First element:", my_series[0])
C:\Users\nidhi\AppData\Local\Temp\ipykernel_16904\804799052.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("The second element:", my_series[1])


Question 2 : Pandas Series From a Dictionary

In [ ]:
# Create a dictionary
data_dict = {'Apple': 3, 'Banana': 2, 'Cherry': 5, 'Date': 1}
# Create a pandas Series from the dictionary
fruits_series = pd.Series(data_dict)
# Print the Series
print(fruits_series)

Question 3 : Pandas DataFrame

In [39]:
# Create a dictionary Of data
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'David'],
'Age': [25, 30, 35, 40],
'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
}
# Create a Pandas DataFrame from the dictionary
df = pd.DataFrame(data)
# Print the DataFrame
print(df)
print("\n",df['Name'])

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   40        Chicago

 0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object


Question 4 : Pandas Methods a.describe() b.head() c.tail()

In [ ]:
# Create a sample DataFrame
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
'Age': [25, 30, 35, 40, 22],
'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago', 'Miami']
}
ind = [10,20,30,40,50]
df = pd.DataFrame(data,index = ind)
print(df)
# Use describe() to get summary statistics
print(" DataFrame Statistics (describe()):")
print(df.describe())
# Use head() to display the first few rows (default is 5)
print("\nFirst 3 rows (head()):")
print(df.head(3))
# Use tail() to display the last few rows (default is 5)
print("\nLast 2 rows (tail()):")
print(df.tail(2))